#!/bin/sh
### BEGIN INIT INFO
# Provides:          mathkernel
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mathkernel
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_start () {
 (cat /usr/share/Mathematica/remotemode.m | /opt/Wolfram/Mathematica/10.0/Executables/wolfram) &
}

do_status () {
 echo "Process ID at: "
 cat /var/run/mathkernel.pid
 echo
 echo "MathLink located at: "
 cat /var/run/mathkernel.link
 echo
}

do_stop () {
 kill -9 `cat /var/run/mathkernel.pid`
 rm /var/run/mathkernel.pid
 rm /var/run/mathkernel.link
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	do_stop
	sleep 4
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: mathkernel [start|stop|status]" >&2
	exit 3
	;;
esac

:

